### ISSUE TITLE
Composer Problem

### ISSUE THREAD

**Issue by dewmguy** [LogansUA/blizzard-api-php-client#12]
I have cpanel and cannot install composer to my account. I tried logging into SSH and everything. My bin directory is read-only.

What can I do? I don't know enough about the requirements for connecting to the blizz api but it seems like a lot of other developers are using composer for their projects.

How can I use this without composer?

**Comment by LogansUA** [comment]
@jerbookins Hello.

You can't use this library without composer because composer pulls another mandatory libraries such as Guzzle etc., but you actually may use [Blizzard API](https://dev.battle.net/) directly simply by using [curl](http://php.net/manual/en/book.curl.php) (some [usefull information](http://www.kliptu.com/free-script/curl-get-post-put-example-in-php)).

You can find all information about Blizzard API [here](https://dev.battle.net/io-docs).

**Comment by dewmguy** [comment]
Thanks for the fast reply. I'll see what I can do without it.

**Comment by LogansUA** [comment]
@jerbookins Good luck :smile:
